name: "Test"
on:
  push:
    branches: ["main", "release*"]
  pull_request: 

jobs:
  test:
    runs-on: macos-13
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.0
    - uses: actions/checkout@v3

    - name: "swift test"
      run: swift test
