name: "Test"
on:
  push:
    branches: ["main", "release*"]
  pull_request: 

jobs:
  test:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3

    - name: "swift test"
      run: swift test
